name: Maven Package

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '7'
        distribution: 'temurin'


    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Publish 
      uses: softprops/action-gh-release@v2
      with:
        files: |
          /home/runner/work/ping/ping/target/*.jar
